dependencies = [
    "flask==3.1.1",
    "flask-cors==6.0.1", 
    "openai==1.93.0",
    "langchain==0.3.26",
    "langchain-openai==0.3.27",
    "faiss-cpu==1.11.0",
    "python-dotenv==1.1.1",
    # ... (all dependencies listed)
]